# Generated by Django 4.1.2 on 2023-04-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeDecor',
            new_name='HomeDcor',
        ),
    ]
