# Generated by Django 4.1.2 on 2023-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_homedecor_homedcor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDecorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('category', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeFurnishingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.TextField()),
                ('category', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeDcor',
            new_name='HomeDecor',
        ),
        migrations.DeleteModel(
            name='HomeImprovement',
        ),
    ]
