# Generated by Django 4.1.2 on 2023-04-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_homedecordetail_homefurnishingdetail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeDecor',
            new_name='HomeDcor',
        ),
    ]
